title = "Open 3D Engine"
disableKinds = ["taxonomy", "taxonomyTerm"]
copyright = "O3DE Authors | Documentation Distributed under CC-BY 4.0"

enableGitInfo = true

[markup.highlight]
style = "paraiso-dark"

[params]
font_awesome_version = "5.12.0"
description = "Open 3D Engine (O3DE) is a multi-platform 3D development engine, bringing together over 30 fully matured and integrated 3D authoring tools, enabling users to build AAA games, cinema quality 3D worlds for video production, and high-fidelity simulations for non-gaming use cases with zero lisencing fees, commercial terms, or disclosure obligations."
favicon = "favicon.png"
repositoryUrl = "https://github.com/o3de/o3de.org"
contentDir = "/content/"

[params.logos]
navbar = "o3de-color.png"

[[params.social]]
name = "Twitter"
url = "#"
icon = "fab fa-twitter"

[[params.social]]
name = "GitHub"
url = "https://github.com/o3de"
icon = "fab fa-github"

[[params.social]]
name = "Discord"
url = "#"
icon = "fas fa-envelope"

[[params.social]]
name = "Slack"
url = "#"
icon = "fab fa-slack"

[[params.fonts]]
name = "Open Sans"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Fira Mono"
sizes = [300, 400, 600, 700]
type = "monospace"

[[params.fonts]]
name = "Open Sans"
sizes = [100, 200, 300, 400, 500, 600, 700]
type = "heading_font"

[[menu.main]]
name = "Download"
url = "/download"
weight = 1

[[menu.main]]
name = "News"
url ="/news"
weight = 2

[[menu.main]]
name = "Community"
url = "#"
weight = 3
identifier = "community"

[[menu.main]]
name = "Community subitem placeholder"
url = "/placeholder"
weight = 1 
parent = "community"

[[menu.main]]
name = "Learn"
url = "#"
weight = 4
identifier = "learn"

[[menu.main]]
name = "Documentation"
url = "/docs"
weight = 1 
parent = "learn"