[build]
publish = "public"
command = "make production-build"

[build.environment]
HUGO_VERSION = "0.75.1"

[context.deploy-preview]
command = "make preview-build"
command = "echo 'User-agent: *\nDisallow: /' > robots.txt"

[context.branch-deploy]
command = "make preview-build"
command = "echo 'User-agent: *\nDisallow: /' > robots.txt"
