[build]
publish = "public"
command = "make production-build"

[context.production.environment]
HUGO_VERSION = "0.75.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"
